import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const navLinkClassName = "text-xl text-white mb-4 mx-4 flex-1 font-mono font-light tracking-widest"
  const [navOpen, setNavOpen] = useState(false)
  const toggleNav = () => {
    setNavOpen(!navOpen)
  }
  return (
    <>
      <Head>
        <title>Din mamma lol</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-blue-500 min-h-screen'>
          <button onClick={toggleNav} className="z-10 aspect-square top-2 left-2 text-center w-12 bg-white fixed rounded-xl text-3xl">O</button>
          <aside className={navOpen ? "border-2 transistion-all duration-500 fixed h-screen bg-red-300" : "h-screen fixed transition-all -translate-x-full border-2 duration-500"}>
            <nav className="mx-8 pt-32 flex flex-col h-full justify-between transition-all duration-500 delay-300 ">
              <p className={navLinkClassName}>Hejjjasdfasdfsafdee</p>
              <p className={navLinkClassName}>Hj</p>
              <p className={navLinkClassName}>Hesadfsadfj</p>
              <p className={navLinkClassName}>Hj</p>
              <p className={navLinkClassName}>H</p>
            </nav>
          </aside>
          <div className="">
              <h1 className='text-white font-mono text-7xl text-center'>Hello everybody</h1>

              <p className='text-xl text-black font-mono'>  
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
                loasfökljgnwljkhzbgh öousdbrgbswdlfhgovleabf
              </p>
          </div>
      </main>
    </>
  )
}
